"""create jobs table

Revision ID: 004b0458df72
Revises: 
Create Date: 2026-06-29 12:27:23.680849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004b0458df72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('minimum_experience', sa.Integer(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_type IN ('full_time', 'part_time', 'contract', 'internship')", name='ck_jobs_employment_type'),
    sa.CheckConstraint('cardinality(preferred_skills) <= 20', name='ck_jobs_preferred_skills_count'),
    sa.CheckConstraint('cardinality(required_skills) BETWEEN 1 AND 20', name='ck_jobs_required_skills_count'),
    sa.CheckConstraint('minimum_experience BETWEEN 0 AND 50', name='ck_jobs_minimum_experience_range'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
