"""create resume contents table

Revision ID: 4d86afcd01f7
Revises: fdcbcf69aa5b
Create Date: 2026-07-18 17:34:40.606043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d86afcd01f7'
down_revision: Union[str, Sequence[str], None] = 'fdcbcf69aa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('pending', 'completed', 'failed')", name='ck_resume_contents_extraction_status'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', name='uq_resume_contents_resume_id')
    )
    op.create_index(op.f('ix_resume_contents_resume_id'), 'resume_contents', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_contents_resume_id'), table_name='resume_contents')
    op.drop_table('resume_contents')
    # ### end Alembic commands ###
