"""create candidate job matches table

Revision ID: 5cadf093cbff
Revises: 8509441f9d14
Create Date: 2026-07-20 15:17:24.070128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cadf093cbff'
down_revision: Union[str, Sequence[str], None] = '8509441f9d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_job_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('resume_profile_id', sa.UUID(), nullable=False),
    sa.Column('job_requirement_profile_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('certification_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('location_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('work_mode_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.Column('analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('source_resume_text_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_resume_parser_version', sa.String(length=50), nullable=False),
    sa.Column('source_job_description_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_job_parser_version', sa.String(length=50), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recommendation IN ('strong_match', 'good_match', 'partial_match', 'weak_match', 'insufficient_data')", name='ck_candidate_job_matches_recommendation'),
    sa.CheckConstraint('certification_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_certification_score_range'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_confidence_score_range'),
    sa.CheckConstraint('education_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_education_score_range'),
    sa.CheckConstraint('experience_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_experience_score_range'),
    sa.CheckConstraint('location_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_location_score_range'),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_overall_score_range'),
    sa.CheckConstraint('skill_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_skill_score_range'),
    sa.CheckConstraint('work_mode_score BETWEEN 0 AND 100', name='ck_candidate_job_matches_work_mode_score_range'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_requirement_profile_id'], ['job_requirement_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_profile_id'], ['resume_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job_matches_candidate_job')
    )
    op.create_index(op.f('ix_candidate_job_matches_candidate_id'), 'candidate_job_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_job_id'), 'candidate_job_matches', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_job_matches_job_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_candidate_id'), table_name='candidate_job_matches')
    op.drop_table('candidate_job_matches')
    # ### end Alembic commands ###
