"""create candidates table

Revision ID: 6b5b2f4fe48b
Revises: 004b0458df72
Create Date: 2026-07-05 16:11:08.971513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5b2f4fe48b'
down_revision: Union[str, Sequence[str], None] = '004b0458df72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('current_role', sa.String(length=150), nullable=True),
    sa.Column('total_experience_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cardinality(skills) <= 50', name='ck_candidates_skills_count'),
    sa.CheckConstraint('total_experience_months BETWEEN 0 AND 720', name='ck_candidates_total_experience_months_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
