"""create resume profiles table

Revision ID: 77a659b25b3c
Revises: 4d86afcd01f7
Create Date: 2026-07-19 14:48:15.775105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77a659b25b3c'
down_revision: Union[str, Sequence[str], None] = '4d86afcd01f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsing_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('parsing_error', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('source_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parsing_status IN ('pending', 'completed', 'failed')", name='ck_resume_profiles_parsing_status'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', name='uq_resume_profiles_resume_id')
    )
    op.create_index(op.f('ix_resume_profiles_resume_id'), 'resume_profiles', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_profiles_resume_id'), table_name='resume_profiles')
    op.drop_table('resume_profiles')
    # ### end Alembic commands ###
