"""add job description and requirement profiles

Revision ID: 8509441f9d14
Revises: 77a659b25b3c
Create Date: 2026-07-20 12:27:55.584355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8509441f9d14'
down_revision: Union[str, Sequence[str], None] = '77a659b25b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requirement_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsing_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('parsing_error', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('source_description_sha256', sa.String(length=64), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parsing_status IN ('pending', 'completed', 'failed')", name='ck_job_requirement_profiles_parsing_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_job_requirement_profiles_job_id')
    )
    op.create_index(op.f('ix_job_requirement_profiles_job_id'), 'job_requirement_profiles', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description')
    op.drop_index(op.f('ix_job_requirement_profiles_job_id'), table_name='job_requirement_profiles')
    op.drop_table('job_requirement_profiles')
    # ### end Alembic commands ###
